workflows:
  ios-build:
    name: iOS Build for V-Card
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync ios
      - name: Build iOS App (Unsigned)
        script: |
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App" --skip-provisioning
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "Matache.alexandru@icloud.com"
